### ISSUE TITLE
Content Overflow On Flip Card

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#114]
## Problem Statememnt
On the member's page, flip card content overflows when the introduction text is too long
![image](https://user-images.githubusercontent.com/67319772/186121292-8c281279-8307-42aa-852c-5772e2e71a38.png)

## possible solution
- set tex overflow to scroll on the flip card
or
- set text-overflow to ellipsis

**Comment by Kritikajain6104** [comment]
Please assign this to me. I can work on it.

**Comment by babboe1** [comment]
Hello [jwardoin](https://github.com/jwardoin)
Are you still working on this issue??

Kindly send a feedback so we know you are still working on it

**Comment by abitsalihu** [comment]
Hey @babboe1 has this issue been fixed? If not I would happily help with it!

**Comment by babboe1** [comment]
> Hey @babboe1 has this issue been fixed? If not I would happily help with it!

No it hasn't,
You can go ahead with the issue,
I will assign it to you now

**Comment by abitsalihu** [comment]
Thank you, I will tackle this tonight and most likely make the PR by tomorrow. :)
