### ISSUE TITLE
Resize Pop Up Menu layout 

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#116]
## Problem statement
- Pop up menu too big when the go-back button is clicked
- Make "Yes / No " option look like a button
- Add green and red background to "No / Yes" button respectively

![image](https://user-images.githubusercontent.com/67319772/186218681-39e5a2c3-4acc-4773-a540-8c475399d1f2.png)

## possible solution
- Add max-width to pop up lay out

**Comment by frantic-dev** [comment]
what height and width do you want the pop up menu to be?

**Comment by babboe1** [comment]
Hello Frantic-dev,
you can use your preference
but it should look something close to this 

![image](https://user-images.githubusercontent.com/67319772/186531154-0174b8c5-cacc-4037-9e6b-8285b34ee6f0.png)

If you have any further questions please don't hesitate to ask 
Looking forward to your PR
