### ISSUE TITLE
Search Bar Not Working

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#117]
## Problem Statement
- Search bar not functioning

### Challenge
- User should be able to search by Name, id, Circle and get result

**Comment by Kd-Here** [comment]
Hello Babboe1 this is my first PR.
Please correct me if I made a mistake.
Resolved the search bar problem.
It's good to go

**Comment by babboe1** [comment]
Hello Kd-Here it's nice to have you here
I am going to reviwe your PR now
