### ISSUE TITLE
Read More Button Points To Wrong Dashboard

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#118]
## Problem Statement
- when read more button is clicked , it opens the dashboard of the previous profile in line

![image](https://user-images.githubusercontent.com/67319772/186222362-71efebaa-e0b2-4aea-b436-bc44789d81c4.png)
when read more (blue arrow) is clicked , it goes to the dash board of previous profile ( red arrow)

**Comment by jacastanon01** [comment]
Hi can I start working on this issue?

**Comment by babboe1** [comment]
Hello jacastanon01,
Yes you can work on this issue

**Comment by jacastanon01** [comment]
PR has been created. The issue was an id number was skipped in the student data json file

**Comment by babboe1** [comment]
Thank you jacastanon01 for working on the issue 
your solution has been merged
