### ISSUE TITLE
Transition Effect On Hover

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#119]
## Problem statement
- add transition effects to tiles on hover
![image](https://user-images.githubusercontent.com/67319772/186355934-86a89c82-66dc-482a-befd-8f9860f5df06.png)

## possible solution
- add transform scale on hover to the buttons

**Comment by christophermorin** [comment]
Hello. I'd like to take this one on.

**Comment by babboe1** [comment]
Hello Christophermorin,
You can go ahead with it,

Looking forward to your PR

**Comment by christophermorin** [comment]
Thank you Abiola. I've submitted the PR. Hopefully it's what you were looking for.
I haven't encountered transform scale() before, so it was fun to learn and it's something I'm excited to add to my projects as well.

**Comment by babboe1** [comment]
I am glad you were able to learn something new Christophermorin,
Thanks for contributing,
I reviewed your PR already and It looks good to me
expect i would like you to make a little change
I ought to have specified it in the issue so i apologize for that
