### ISSUE TITLE
Noticed some typos on the web page plus student contribution

### ISSUE THREAD

**Issue by Adephumie** [Cloudlordd/Cloudlord-and-pals#12]
While going through the website to see how I can contribute as an AltSchool Student to the project, I noticed some typos in some areas and would like to work on them. Typos such as spaces after commas, spelling errors, etc.
<img width="1280" alt="Screenshot 2022-08-10 at 10 29 15" src="https://user-images.githubusercontent.com/64367471/183848191-e69ec37d-7670-4261-b638-4d8705b55438.png">
<img width="1280" alt="Screenshot 2022-08-10 at 10 34 55" src="https://user-images.githubusercontent.com/64367471/183848304-119fe2a8-b9d3-4e9f-9fd7-1b1d54bdcef1.png">
<img width="1280" alt="Screenshot 2022-08-10 at 10 35 32" src="https://user-images.githubusercontent.com/64367471/183848384-4e5c278a-4cb0-4bef-b005-9ee5bc310e49.png">

**Comment by buhari44** [comment]
Welldone,Try to finish up your profile. KUDOS
