### ISSUE TITLE
Correct Overstretched Image

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#121]
## Problem Statement
- Display Picture looks overstretched

![image](https://user-images.githubusercontent.com/67319772/186487008-d41ab734-d63a-48ab-b5dc-0163933e78b2.png)

## possible solution
- Hint: to get a perfect circle, Height and Width has to be the same
- Work with (20vh)

**Comment by rcmtcristian** [comment]
Hello. I'd like to take this one on.

**Comment by babboe1** [comment]
Hello rcmtcristian
You can go ahead
