### ISSUE TITLE
Transition Effect On Hover

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#124]
## Problem statement
- add transition effects to social media icons on hover, located at the footer of home page and members page

![image](https://user-images.githubusercontent.com/67319772/186607313-481e45b3-fbdc-44ad-9b1f-63401ec9a278.png)

## Possible solution
- transform scale(1.2), transition timing 0.5s

**Comment by Marian1200** [comment]
Hey I am interested in taking this one

**Comment by babboe1** [comment]
Hello Marian1200,
You can Go ahead
