### ISSUE TITLE
Pointer on Hover state

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#136]
## Problem Statement
- add pointer cursor when hovering menu button located on the dash board page

![image](https://user-images.githubusercontent.com/67319772/187032560-c780b983-47f0-4f9b-a0ea-bebec649f783.png)

**Comment by Kritikajain6104** [comment]
I want to work on this issue . Please assign this issue to me.

**Comment by williamwebs** [comment]
I see your have the cursor pointer issue upon hovering on the dashboard. I will love to resolve this.

**Comment by irfen-mi** [comment]
@babboe1 hello, its just took 2 mints assign me this.

**Comment by babboe1** [comment]
Hello Everyone
Than you very much for showing Interest in contributing to this Open source project

However, [Kritikajain6104](https://github.com/Kritikajain6104) made the request to work on this issues first,
so i will be assigning the task to the individual

[Kritikajain6104](https://github.com/Kritikajain6104) you have the period of 48hrs to work on this issue
If a PR hasn't been submitted in 48hrs
The issue will be reassigned to the next person in line
thank you

**Comment by Kritikajain6104** [comment]
Got it, thanks!
