### ISSUE TITLE
Project Title Text overflow

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#153]
## Problem Statement
- Project title overflows when text is too long
![image](https://user-images.githubusercontent.com/67319772/189607615-bc46e741-259d-4fc2-8cf2-83ac6774dab9.png)

## Possible Solution
![image](https://user-images.githubusercontent.com/67319772/189610973-99e0c78e-c1d5-4d5e-9a62-516931254ad7.png)

- remove Height and width
- set padding to 1rem
- set max-width to 300px

**Comment by abitsalihu** [comment]
Hey, I would like to work on this issue!

**Comment by babboe1** [comment]
You are good to go on this abitsalihu

**Comment by abitsalihu** [comment]
Okay @babboe1, thanks :)
