### ISSUE TITLE
[ENHANCEMENT] The "Alt School" logo is too small when viewed in tablet size!

### ISSUE THREAD

**Issue by abitsalihu** [Cloudlordd/Cloudlord-and-pals#155]
I noticed that when someone views the website in tablet size the logo is too small.

Below is a video of the issue.

https://user-images.githubusercontent.com/94648837/189758243-083f47bf-b777-44b4-87ad-efa1a5f736e6.mov

**Comment by abitsalihu** [comment]
Hey, I would like to work on this issue too. :)

**Comment by mk-sdev** [comment]
Can I help?

**Comment by babboe1** [comment]
Hello abitsalihu, Its its okay with you i would like mkaletaa to handle the issue, since this is a First Time contribution

Hello mkaletaa,
You can Go ahead with this issue , Looking forward to your PR

**Comment by abitsalihu** [comment]
@babboe1  no problem for me, let her do it.🙂
