### ISSUE TITLE
[ENHANCEMENT] Some of the images in flip cards, don't have images[no src].

### ISSUE THREAD

**Issue by abitsalihu** [Cloudlordd/Cloudlord-and-pals#157]
Until these people put their own images up I think there should be some default images so the UI of the website does not look bad.

Below are two pictures of the two images I'm talking about.

<img width="1437" alt="Screen Shot 2022-09-13 at 11 52 02" src="https://user-images.githubusercontent.com/94648837/189871721-bf0c0bf0-0852-43bf-9f5e-e12fd4a856eb.png">
<img width="1437" alt="Screen Shot 2022-09-13 at 11 51 29" src="https://user-images.githubusercontent.com/94648837/189871728-70cad14b-409a-41a4-bf10-0e7d8453e4d8.png">

**Comment by abitsalihu** [comment]
@babboe1 i would like to fix this issue, I also applied for another issue if you can check it. :)

**Comment by babboe1** [comment]
Ok abisalihu
You can Go ahead with this issue
