### ISSUE TITLE
Image elements do not have explicit width and height

### ISSUE THREAD

**Issue by MargretEdeh** [Cloudlordd/Cloudlord-and-pals#40]
while analyzing your website using light house, i realized that the alt school logo does not have width and height which causes page layout shift. i want to try solving this

**Comment by buhari44** [comment]
You are free to work on it,make sure the branch name and commit align with what you are doing

**Comment by babboe1** [comment]
Hello MargetEdeh, as this been fixed yet
If not I would like to take it up
