### ISSUE TITLE
The 'read more' button at the back of the profile card does not work for all members.

### ISSUE THREAD

**Issue by Dalu46** [Cloudlordd/Cloudlord-and-pals#56]
I noticed that the **Read More** button does not work for all members. It only points to the profile of few members, rather than all.
<img width="272" alt="Screenshot 2022-08-13 at 09 45 45" src="https://user-images.githubusercontent.com/93771818/184476446-68847582-b0c9-4129-bc12-983a9f02d73b.png">

**Comment by buhari44** [comment]
FIXED, YOU CAN CHECK AGAIN
