### ISSUE TITLE
Text visibility issue

### ISSUE THREAD

**Issue by Dalu46** [Cloudlordd/Cloudlord-and-pals#74]
I noticed that the text "yes" and "no" on the dashboard page isn't really clear.
<img width="1270" alt="Screenshot 2022-08-15 at 08 57 33" src="https://user-images.githubusercontent.com/93771818/184598148-bcfbae6b-affa-47f1-bec9-9d3f483bf125.png">

**Comment by Dalu46** [comment]
Hi @buhari44 I'd be happy to work on this.

**Comment by buhari44** [comment]
Go on and perform your magic ✨, can't wait to merge the pr
