### ISSUE TITLE
Button doesn't point to any page

### ISSUE THREAD

**Issue by Dalu46** [Cloudlordd/Cloudlord-and-pals#75]
When a user clicks on the "dashboard" on the dashboard homepage, the "Go back" button on the dashboard page doesn't point to any page.
<img width="267" alt="Screenshot 2022-08-15 at 09 01 54" src="https://user-images.githubusercontent.com/93771818/184599079-27835eef-b356-4026-8e21-ce3b118f93b2.png">

**Comment by Dalu46** [comment]
Hi @buhari44 I'd love to work on this.

**Comment by buhari44** [comment]
Fine, go ahead
Note that the go back button is to display an alert box with two buttons that ask the user if he want to proceed to home or stay on the dashboard

**Comment by Dalu46** [comment]
Thanks. Also I have a question. Given that the user gets to the dashboard page from the "pals" page, wouldn't it be better to point the "Go back" button to the "pals" page? What do you think?
