### ISSUE TITLE
Content best practices is not Optimized

### ISSUE THREAD

**Issue by Joseph-Alagi-Okebe** [Cloudlordd/Cloudlord-and-pals#82]
![Screenshot 2022-08-16 000553](https://user-images.githubusercontent.com/63665248/184735793-2760c077-0daa-4d68-8002-00782430f476.png)
I analyzed the website using lighthouse and I found out that the SEO for the website is not optimized because the website lacked meta document.
I can fix this issue, should I go ahead and fix it.

**Comment by buhari44** [comment]
Please go ahead and fix it

**Comment by babboe1** [comment]
Hello Joseph-Alagi, 
Its been 12 days since you requested to work on this issue
Are you still working on it??

**Comment by Joseph-Alagi-Okebe** [comment]
Yeah, I'm still on it.

**Comment by babboe1** [comment]
Hello Joseph-Alagi
Please you have 48hrs left to work on this issue,
If a PR isn't submitted within the time frame 
You will be unassigned and this issue becomes open for anyone considering to work on it
