### ISSUE TITLE
Profile Page not responsive on mobile

### ISSUE THREAD

**Issue by babboe1** [Cloudlordd/Cloudlord-and-pals#85]
This entire Project in itself is a very nice Idea,
I can help fix this part of the page and make it responsive on mobile, such that the sidebar is going to be displayed as an  Overlay when the menu button is clicked
If you are okay with me helping, all you have to do is assign me to the task to ensure I get a notification and I will get it done as soon as I can

![image](https://user-images.githubusercontent.com/67319772/184936252-4baf4fc9-26cc-44ff-9d15-ecb77c33f3da.png)

**Comment by buhari44** [comment]
You are good to go boss, i cant wait for the outcome

**Comment by babboe1** [comment]
Ok great
I will start working on it as soon as possible
you will hear from me tomorrow

**Comment by buhari44** [comment]
Please, can you check the profile pictures on mobile, the pictures are not in shape

**Comment by babboe1** [comment]
Can I get more description as soon as possible??
Something like a picture to explain what you are saying would work

**Comment by babboe1** [comment]
Buhari44,
Are you referring to this profile picture part of  the page
![image](https://user-images.githubusercontent.com/67319772/185517787-21befe62-6a9b-4163-8145-44e460cacc0d.png)

If It is,
Kindly create an issue and assign me to it, so i could get a notification on my mail and start working on it as soon as possible
